name: 'Metagen GitHub Action'
description: 'Port of Unity `.meta` file generator `metagen` to JavaScript as GitHub Action.'
branding:
    icon: 'anchor'
    color: 'green'
inputs:
  seed:
    description: 'seed string, e.g. package name. defaults to cwd'
    required: false
  files:
    description: 'files to generate .meta files for. default: use package.json .files as input'
    required: false
outputs:
  metafiles:
    description: 'list of generated metafiles'
runs:
  using: 'node12'
  main: 'index.js'
